package ro.hanca.cristian.munichcity.models;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import ro.hanca.cristian.munichcity.models.POI;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "POI".
*/
public class POIDao extends AbstractDao<POI, Long> {

    public static final String TABLENAME = "POI";

    /**
     * Properties of entity POI.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "Id");
        public final static Property SubTypeId = new Property(1, Long.class, "SubTypeId", false, "SubTypeId");
        public final static Property Lat = new Property(2, Double.class, "Lat", false, "Lat");
        public final static Property Lon = new Property(3, Double.class, "Lon", false, "Lon");
        public final static Property Name = new Property(4, String.class, "Name", false, "Name");
    };

    private DaoSession daoSession;

    private Query<POI> subType_EntriesQuery;

    public POIDao(DaoConfig config) {
        super(config);
    }
    
    public POIDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"POI\" (" + //
                "\"Id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"SubTypeId\" INTEGER," + // 1: SubTypeId
                "\"Lat\" REAL," + // 2: Lat
                "\"Lon\" REAL," + // 3: Lon
                "\"Name\" TEXT);"); // 4: Name
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"POI\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, POI entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long SubTypeId = entity.getSubTypeId();
        if (SubTypeId != null) {
            stmt.bindLong(2, SubTypeId);
        }
 
        Double Lat = entity.getLat();
        if (Lat != null) {
            stmt.bindDouble(3, Lat);
        }
 
        Double Lon = entity.getLon();
        if (Lon != null) {
            stmt.bindDouble(4, Lon);
        }
 
        String Name = entity.getName();
        if (Name != null) {
            stmt.bindString(5, Name);
        }
    }

    @Override
    protected void attachEntity(POI entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public POI readEntity(Cursor cursor, int offset) {
        POI entity = new POI( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // SubTypeId
            cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2), // Lat
            cursor.isNull(offset + 3) ? null : cursor.getDouble(offset + 3), // Lon
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // Name
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, POI entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSubTypeId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setLat(cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2));
        entity.setLon(cursor.isNull(offset + 3) ? null : cursor.getDouble(offset + 3));
        entity.setName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(POI entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(POI entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "Entries" to-many relationship of SubType. */
    public List<POI> _querySubType_Entries(Long SubTypeId) {
        synchronized (this) {
            if (subType_EntriesQuery == null) {
                QueryBuilder<POI> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.SubTypeId.eq(null));
                subType_EntriesQuery = queryBuilder.build();
            }
        }
        Query<POI> query = subType_EntriesQuery.forCurrentThread();
        query.setParameter(0, SubTypeId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getSubTypeDao().getAllColumns());
            builder.append(" FROM POI T");
            builder.append(" LEFT JOIN SubType T0 ON T.\"SubTypeId\"=T0.\"Id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected POI loadCurrentDeep(Cursor cursor, boolean lock) {
        POI entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        SubType SubType = loadCurrentOther(daoSession.getSubTypeDao(), cursor, offset);
        entity.setSubType(SubType);

        return entity;    
    }

    public POI loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<POI> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<POI> list = new ArrayList<POI>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<POI> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<POI> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
